"""Initial migration: create scan_sessions table

Revision ID: e6a1d4093a1a
Revises: 
Create Date: 2025-10-22 13:57:15.449821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6a1d4093a1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='세션 ID (UUID)'),
    sa.Column('target', sa.String(length=255), nullable=False, comment='스캔 대상 IP 주소'),
    sa.Column('scan_type', sa.Enum('QUICK', 'STANDARD', 'FULL', name='scantype'), nullable=False, comment='스캔 유형 (quick/standard/full)'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='scanstatus'), nullable=False, comment='스캔 상태'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='진행률 (0-100)'),
    sa.Column('current_step', sa.String(length=100), nullable=True, comment='현재 진행 중인 단계'),
    sa.Column('error', sa.Text(), nullable=True, comment='에러 메시지 (실패 시)'),
    sa.Column('ports', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='발견된 포트 목록'),
    sa.Column('vulnerabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='발견된 취약점 목록'),
    sa.Column('risk_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='위험도 평가 결과'),
    sa.Column('remediation', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='해결 방안'),
    sa.Column('report', sa.Text(), nullable=True, comment='최종 보고서 (Markdown)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 시간'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='스캔 시작 시간'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='스캔 완료 시간'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='마지막 업데이트 시간'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_sessions_created_at'), 'scan_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_sessions_id'), 'scan_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_scan_sessions_status'), 'scan_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_scan_sessions_target'), 'scan_sessions', ['target'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_sessions_target'), table_name='scan_sessions')
    op.drop_index(op.f('ix_scan_sessions_status'), table_name='scan_sessions')
    op.drop_index(op.f('ix_scan_sessions_id'), table_name='scan_sessions')
    op.drop_index(op.f('ix_scan_sessions_created_at'), table_name='scan_sessions')
    op.drop_table('scan_sessions')
    # ### end Alembic commands ###
